title: Clinical Data Science
email: clinical-data-science.radiologie@med.uni-muenchen.de
name: Clinical Data Science
description: "A place for thoughts, discussions and opinions on topics related to academia in general and AI in radiology in particular."
url: https://clinicaldatascience.github.io/
teaser: /assets/images/corevalues.jpeg
logo: /assets/images/cds_dark_square.png
masthead_title: Clinical Data Science

author:
  name: Clinical Data Science
  avatar: "/assets/images/cds_dark_square.png"
  bio: We are a research group within the department of radiology at LMU University Hospital. We focus on machine learning and AI in radiology.  # Note: Markdown is allowed
  location: LMU Munich
  links:
    - label: "Homepage"
      icon: "fas fa-fw fa-link"
      url: "https://www.lmu-klinikum.de/radiologie/forschung/clinical-data-science/0e8a3ac188dad3f9"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ClinicalDataScience"

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      header:
        show_overlay_excerpt: false
        overlay_filter: 0.5
  

minimal_mistakes_skin: "dirt" # "dark", "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# hide rss logo in the footer
atom_feed:
  hide: true

# search bar in the header
search: true
lunr:
  search_within_pages: true
  search_full_content: true

# footer
footer:
  links:
    - label: "Homepage"
      icon: "fas fa-fw fa-link"
      url: "https://www.lmu-klinikum.de/radiologie/forschung/clinical-data-science/0e8a3ac188dad3f9"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ClinicalDataScience"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

paginate: 3

include: ["_pages"]